"""empty message

Revision ID: 7968c7db0609
Revises: 8d422ddcff00
Create Date: 2022-11-02 23:13:32.515319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7968c7db0609'
down_revision = '8d422ddcff00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
