"""empty message

Revision ID: 8d422ddcff00
Revises: a2b8632e8ef2
Create Date: 2022-11-02 23:09:35.694312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d422ddcff00'
down_revision = 'a2b8632e8ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'area_id')
    # ### end Alembic commands ###
