"""empty message

Revision ID: 9687044c7352
Revises: 27d7c6ff4ee2
Create Date: 2022-10-31 09:34:43.147035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9687044c7352'
down_revision = '27d7c6ff4ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'venue', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.alter_column('venue', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
